In [57]:
# Image to Numpy Array
#I take only 10 images and convert it into numpy array after resizing images you can check by running this code

import numpy as np
from PIL import Image
import os

for f in os.listdir('.'):
    if f.endswith('.jpg'):
        
        print(f)
        
        i = Image.open(f)
        im.show()
        print(im)
        
        im=i.resize((200,200))
        im_np = np.array(im)
        
        print(im_np)  
        print(im_np.shape)

sk1.jpg
<PIL.Image.Image image mode=RGB size=200x200 at 0x246CEC6EB00>
[[[ 65  47   0]
  [137 116  25]
  [123  98   6]
  ...
  [ 55  76   0]
  [ 63  75  11]
  [ 54  66   2]]

 [[106  87  18]
  [125 104  15]
  [144 119  27]
  ...
  [ 69  88   6]
  [ 80  92  26]
  [ 72  84  18]]

 [[101  83  17]
  [ 54  34   0]
  [104  81   0]
  ...
  [ 76  93   1]
  [ 70  80  11]
  [ 70  80  11]]

 ...

 [[ 19  43   0]
  [ 52  56  21]
  [ 82  61  42]
  ...
  [ 53  64   0]
  [ 57  84   5]
  [ 65  92  13]]

 [[ 35  58   0]
  [ 73  80  46]
  [ 77  62  41]
  ...
  [ 66  79   0]
  [ 44  71   0]
  [ 54  81   2]]

 [[ 40  61   2]
  [ 19  30   0]
  [ 29  21   0]
  ...
  [ 55  68   0]
  [ 59  86   7]
  [ 58  85   6]]]
(200, 200, 3)
sk10.jpg
<PIL.Image.Image image mode=RGB size=200x200 at 0x246CCF35AC8>
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[